export const stitchCatalog = [
  {
    id: '1',
    name: 'KINETIC-9 CORE',
    price: 1299,
    category: 'Processors',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAPu6n-0x9t1RQWrOKyC30njnZK93G344Ki5eEKvRMEaTO5TTUYtTsOpS6op8-vXfuqmg_FErNC-oGN4CO4NFL3QiUPaCxt5cuD7I0UkMU_wpXqcX7vcEIX1gUZ9Nui5KzWqrgEdHbxvjYt_xgUj1UkGhJ9X8owjs5WUXSUKHsrsmEvz_8CAjdkU2jc-zJibSrBdmlo1Jy2Q3py-fVIAR4K2Pb8gzTvJHBj49KTt_GyoLu2hZRm0TAZYKJNez-16cUWkyAgunZLhvY',
    rating: 4.8,
    stock: 50,
    sku: 'SKU - K9-CPU-X',
    description: 'Enterprise-grade silicon optimized for LLM inference and real-time data flow.',
    specs: {
      Architecture: 'Forge Vector 9',
      Process: '3nm',
      TDP: '110W',
      Cooling: 'Hybrid vapor array',
    },
  },
  {
    id: '2',
    name: 'VOID BLADE 2TB',
    price: 450,
    category: 'Storage Blades',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8OQ4Uf9mqB0Nt5Ls2kMbf-6qmEToQvsBY9fkklQJysy3or88KCoC_zur57Eao5SCMJSKKDBhozk245ex_h2rah5amMxt5qJuOsrjPixvUeP63LJVBITAsiyT2oU55O_sasa3-Rq-j7AztImrlwTQfAY-kCsoXPTIvoUJ19un4AE79GgD178B50lVVVFZHJw3luUmiW9zisUWKku282WboL71p-iP9tl_8OXj0noTFc60VFcbjYod8DlqrqYvyYjFyvojZgUmHdDU',
    rating: 4.9,
    stock: 24,
    sku: 'SKU - SB-2-T',
    description: 'Ultra-low latency NVMe storage module with hardware-level encryption and cache acceleration.',
    specs: {
      Capacity: '2TB',
      Interface: 'PCIe 5.0',
      Read: '14,500 MB/s',
      Write: '12,000 MB/s',
    },
  },
  {
    id: '3',
    name: 'SYNAPSE LINK',
    price: 275,
    category: 'Neural Units',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCY-aEKavEK6g_g6bNORspcgFonOP9Q-v60JE38CEFbkb7KBKTuBaZk3h8Utyc0afAKgc5hS68yo0gw5pnfaXRwG2fGNNNxlyDRMLM9u8THn5crpXpfTWpgQPYT97uQHABwoRtb8UQF3hMI07uYYKTy9fg58BFJ44oQnnGoVQdJSUNB2UFwdZiXAWVV-6QPf4ltR5l7TtKYd6sCR1BbNdNayYD1EZCzKHPoRUcyj4Bv468cCRqGQqF-nmNNIHgeHtL0m8QQTkpMONE',
    rating: 4.7,
    stock: 62,
    sku: 'SKU - SN-CNV-X',
    description: 'High-bandwidth interconnect for distributed computing arrays and neural systems.',
    specs: {
      Channels: '16',
      Latency: '< 1ms',
      Throughput: '80Gb/s',
      Mode: 'Fabric sync',
    },
  },
  {
    id: '4',
    name: 'ATLAS MEMORY 64G',
    price: 390,
    category: 'Memory Modules',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsIgnGPhMY8PYDVpFJLthIeJdeQT3XXh_csvq7e5eWlUtiskY29NcxAA6CjKgPIZ0UsDA6hCUGkblP7BCcG58thhCTMLNnfIVQX0jI-hZcM5KZ2tpqQIap5C2JXtFKZAFjIJVaxaRExWWsGrcNm9HsMY2_RdvrQZFjdz0axPNOCvqVMX57lzoDlFi59_r286CyeiG3fkKwoRsQNV_YLLziJh_exHeT72hlZ2XWf7gIu9ZVx0fnHEd9aQbHftOUpPKCvLJSj14QnEs',
    rating: 4.6,
    stock: 31,
    sku: 'SKU - AM-64-DDR',
    description: 'ECC-ready memory module for mission-critical applications and high-density data sets.',
    specs: {
      Capacity: '64GB',
      Timing: 'CL30',
      Type: 'DDR5 ECC',
      Voltage: '1.25V',
    },
  },
  {
    id: '5',
    name: 'NEURAL CORE X',
    price: 2150,
    category: 'Neural Units',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAmhRABPVKYa7o6KPtWg3E6kFffI5ar0UErAGgvj2ApvHE4vOE1h5G87h9AGHorKH_oros6kZeOa4HqIB5wiTFg1Ivb7RDO_Ezr1_m4z9mEfKZGIoHfQJW1RqxAdHe8J1Csb3eXbNEalgP64wJY-ulPwkWb35Mvl8qFmE10YnWjWQnhhywCtnF4BljocKFNhUoDp_gbUxOteeMzscC0OvUHdJA7QPl0-A7WGiCCyw_7K3WkKhg6La2v3CVfiQbTkk2aXdy-uuiYiGU',
    rating: 4.9,
    stock: 12,
    sku: 'SKU - NC-X-AI2',
    description: 'Dedicated tensor accelerator designed for training small-scale models on the edge.',
    specs: {
      Cores: '4096 tensor lanes',
      Memory: '48GB',
      Bus: 'Gen5 x16',
      Cooling: 'Active mesh',
    },
  },
  {
    id: '6',
    name: 'TITAN CHASSIS',
    price: 599,
    category: 'Processors',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNqaJSbHSAw99yAahUbddvojshk2Mzl1I-ILedevaBp0AbgvNyVJRsbg4_G5kGcAHOJSIpv7XInFRF55P75zA-ZTVoOE4jzGM7tbbjxl6nrvNtTNslwLEtqDB2KhZzymcPbTQA6bjBq2Lb7-3HVSpNqGJCwPpsnwY3FgEn-ordqWczCuMdrSP3yCZVjqb-WDg8jeXdzMzFd4dlO6PcjiXZlA_pvexzGqHCTPgpb_Xe4MqtvZng4qm9KIAyuMwsPsgxXDTkLm6E65s',
    rating: 4.5,
    stock: 18,
    sku: 'SKU - TC-M1-BLK',
    description: 'Modular rack-mount housing with integrated liquid cooling and smart power lanes.',
    specs: {
      Bays: '7 modular slots',
      Material: 'Anodized alloy',
      Cooling: 'Dual flow',
      Power: '1000W smart bus',
    },
  },
  {
    id: '7',
    name: 'KEY-01 CORE',
    price: 249,
    category: 'Accessories',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCqaXRVCdduQxO26ax-DHMXCMKQtMHwMJcRPciTbLbA0fTL7_DpLyXB10OWBfmiFLEKIkQm4r2fnAe4jekWLl8JCV85hxYExKVyiKBGXUHrKPX1WBzEjy9wVD29C5BJ75gPufpZlKe_mul5GEV6UkBHjK5E5FuMbmnq8VUCmCalmskOyiO0THzguOeByrqagDRGR0zhdtIVScABrjMAdEmv3k5RdnNJQVjb_f9qn41OJM_Z2Up4PhQuUVE41FmWZboWQCV0VnU9nvQ',
    rating: 4.7,
    stock: 40,
    sku: 'SKU - KEY-01',
    description: 'Low-profile mechanical keyboard engineered for quiet actuation and rapid command entry.',
    specs: {
      Switches: 'Forge linear',
      Layout: '80%',
      Latency: '<0.5ms',
      Interface: 'USB-C',
    },
  },
  {
    id: '8',
    name: 'AUDIO-P1 PRO',
    price: 399,
    category: 'Audio',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBfkm2iSjy_78I4WLz1BKP1LCv8roU9bgEDqkbCu-KSchjfR5WXu1lhGWtu-aZahiwEppECYlg07GjvpwXBiRg0lOjJYYhKUmYm5KxNu6TijP6JCXPjhuoJlYf8kUWoh7dKD_lD4ke2p2c3CS3sXUUIkKT5B8CUL6X_d5AKYWqKjVqcpsHb6Z6bGOTgT5SNdjO9L0tU8t1PxHICz0r-3r6yK7VPpiLc_DI_2H6lPgx4wAzjHfcU_acAUhsfT_AlYoTRQ-Y7oD3PRy4',
    rating: 4.8,
    stock: 26,
    sku: 'SKU - AP1-PRO',
    description: 'Studio-grade headset with spatial tuning for focus sessions, streaming, and deep work.',
    specs: {
      Drivers: '50mm planar',
      Response: '10Hz-40kHz',
      Mode: 'Wired / DAC',
      Finish: 'Matte black',
    },
  },
  {
    id: '9',
    name: 'FORGEBOOK X',
    price: 1899,
    category: 'Hardware Systems',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBiVl8FALZEJUgTJb8crp72Ywrw1fc2WUKb0s6dOII4Wlzk0npamu4ownelCyiQoExA06gGlyR4Do-RuiWxNg6ylKX0HT5xe6D3EpIJj_VLV6AA7_7Eda7lmPxWbno-GinyTH-8s8iTBl2Ci1lr7W4vT4LRYKY6tTlae8Pg6y6FK-hfpjxf8BKX3AuTWFEJZuqxed_F6fd-HcIRHEW7w9pvchbrzd-RqDRZROsgGEud3rgkoB-W21oKShXnNar5xtleSTyob5ylwhk',
    rating: 4.9,
    stock: 9,
    sku: 'SKU - FBX-16',
    description: 'Portable workstation with forge-tuned thermals, OLED panel, and all-day creator performance.',
    specs: {
      Display: '16-inch OLED',
      CPU: 'Forge Vector 8',
      Memory: '32GB',
      Storage: '2TB NVMe',
    },
  },
  {
    id: '10',
    name: 'VISION-4K PANEL',
    price: 899,
    category: 'Displays',
    image_url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDjuspI_w6sjvLHOrZp19TrLXb0Pug6LE7pH3e1uGQU5kj72CkF9TqLk84pJV0dco-ftggTljaJIOBzOksMMomBWb1njAftLGIlMQq06G3sX-1A8FJ2K8Nc1mNWc7NAmJDirbjD3eSDRK8n4Y4vPO29a4NVMfFzewqOuSwxL0tFbwiupcMCwUyI5aSEsqKqjLoD2lI9ymxO_YzapZF_VsWBQYyTRFA3VwpeconKN25c97RAJZCwQX4hmyxRTyVl77sDqeLx4bhmKYU',
    rating: 4.8,
    stock: 14,
    sku: 'SKU - V4K-27',
    description: 'Color-accurate 4K display built for editing, interface work, and premium desk symmetry.',
    specs: {
      Size: '27-inch',
      Refresh: '144Hz',
      Panel: 'IPS Black',
      'I/O': 'USB-C hub',
    },
  },
  {
    id: '11',
    name: 'CARBON-X MK.III',
    price: 3200,
    category: 'Hardware Systems',
    image_url: 'https://images.unsplash.com/photo-1593642702909-dec73df255d7?auto=format&fit=crop&w=1200&q=80',
    rating: 4.9,
    stock: 6,
    sku: 'SKU - CXM3-BLK',
    description: 'Aerospace-grade desktop tower with integrated thermal zoning for sustained workstation throughput.',
    specs: {
      Chassis: 'Carbon shell',
      Cooling: 'Tri-zone liquid',
      GPU: 'Forge RTX class',
      Build: 'Custom assembled',
    },
  },
  {
    id: '12',
    name: 'HORIZON-S DISPLAY',
    price: 1450,
    category: 'Displays',
    image_url: 'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?auto=format&fit=crop&w=1200&q=80',
    rating: 4.8,
    stock: 11,
    sku: 'SKU - HSD-32',
    description: 'Ultrawide 8K display with deep contrast and zero-frame industrial finishing.',
    specs: {
      Size: '32-inch ultrawide',
      Panel: 'OLED',
      Resolution: '8K',
      Stand: 'Forged alloy',
    },
  },
  {
    id: '13',
    name: 'NEURAL-TAB PRO',
    price: 890,
    category: 'Accessories',
    image_url: 'https://images.unsplash.com/photo-1585790050230-5dd28404ccb9?auto=format&fit=crop&w=1200&q=80',
    rating: 4.7,
    stock: 21,
    sku: 'SKU - NTP-12',
    description: 'Pressure-sensitive drafting surface for rapid architectural and system design workflows.',
    specs: {
      Surface: '12K pressure',
      Pen: 'Magnetic stylus',
      Finish: 'Ceramic matte',
      Sync: 'Low-latency BLE',
    },
  },
]

export const stitchCategories = ['All', 'Processors', 'Memory Modules', 'Neural Units', 'Storage Blades']
